color 02
md test
cd test
xcopy /y  "C:\Users\owner\desktop\pyzba.py" "C:\Users\owner\desktop\test"
xcopy /y  "C:\Users\owner\desktop\mkmaster.py" "C:\Users\owner\desktop\test"
start python "mkmaster.py"
pause "you sure"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
start python "pyzba.py"
pause "press any to del"
del /q *.*
cd "C:\Users\owner\desktop"
del /q test
pause "done"